name: e2e-parallel-destroy-only

on:
  workflow_dispatch:
    inputs:
      TFDestroy:
        description: 'Destroy TF Automatically (false/true) - Default: true'
        required: true
        default: 'true'

concurrency: e2e-parallel-destroy

jobs:
  deploy:
    name: Run e2e test
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - example_path: examples/agones-game-controller
          - example_path: examples/fargate-serverless
          - example_path: examples/argocd
          - example_path: examples/ipv4-prefix-delegation
          - example_path: examples/ipv6-eks-cluster
          - example_path: examples/karpenter
          - example_path: examples/multi-tenancy-with-teams
          - example_path: examples/stateful
          - example_path: examples/vpc-cni-custom-networking

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup backend
        # Un-comment remote backend for use in workflow
        run: sed -i "s/# //g" ${{ matrix.example_path }}/versions.tf

      - name: Auth AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Destroy
        working-directory: ${{ matrix.example_path }}
        run: |
          terraform init -upgrade=true
          terraform destroy -target=module.eks_blueprints_kubernetes_addons  -no-color -input=false -auto-approve
          terraform destroy -target=module.eks_blueprints  -no-color -input=false -auto-approve
          terraform destroy -target=module.eks -no-color -input=false -auto-approve
          terraform destroy -no-color -input=false -auto-approve
